#!/usr/bin/env node
/**
 * Build src/data/guests.js from a CSV export of the couple's guest list.
 *
 *   npm run guests:import -- guests.csv
 *
 * Expected columns (header row required, order and case don't matter; any
 * column not listed is ignored):
 *
 *   name          required — as it should appear over the hero video
 *   salutation    optional — defaults to "Dear"
 *   seats         optional — defaults to 2
 *   lucky         optional — lucky-draw number
 *   note          optional — private line shown only on that invitation
 *   slug          optional — supply to pin a URL; otherwise generated from name
 *
 * Slugs are generated by stripping Vietnamese diacritics, so
 * "Ms. Trần Thị Bảo Ngọc" becomes "ms-tran-thi-bao-ngoc". Existing slugs are
 * never silently changed: pass a `slug` column to keep links already sent out
 * stable if a name is later corrected.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { argv, exit } from "node:process";

const source = argv[2];
if (!source) {
  console.error("Usage: npm run guests:import -- <path-to.csv>");
  exit(1);
}

/** Minimal RFC-4180 parser — handles quoted fields, embedded commas, newlines. */
function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = "";
  let quoted = false;

  for (let i = 0; i < text.length; i++) {
    const char = text[i];

    if (quoted) {
      if (char === '"') {
        if (text[i + 1] === '"') {
          field += '"';
          i++;
        } else {
          quoted = false;
        }
      } else {
        field += char;
      }
      continue;
    }

    if (char === '"') quoted = true;
    else if (char === ",") {
      row.push(field);
      field = "";
    } else if (char === "\n" || char === "\r") {
      if (field !== "" || row.length) {
        row.push(field);
        rows.push(row);
        row = [];
        field = "";
      }
      if (char === "\r" && text[i + 1] === "\n") i++;
    } else field += char;
  }

  if (field !== "" || row.length) {
    row.push(field);
    rows.push(row);
  }
  return rows;
}

function slugify(value) {
  return value
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "") // strip combining tone marks
    .replace(/đ/g, "d")
    .replace(/Đ/g, "D")
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

const rows = parseCsv(readFileSync(source, "utf8")).filter((r) =>
  r.some((cell) => cell.trim() !== ""),
);
if (rows.length < 2) {
  console.error("No data rows found.");
  exit(1);
}

const header = rows[0].map((h) => h.trim().toLowerCase());
const col = (name) => header.indexOf(name);
const idx = {
  name: col("name"),
  salutation: col("salutation"),
  seats: col("seats"),
  lucky: col("lucky"),
  note: col("note"),
  slug: col("slug"),
};

if (idx.name === -1) {
  console.error(`Missing required "name" column. Found: ${header.join(", ")}`);
  exit(1);
}

const seen = new Map();
const guests = [];

for (const [i, row] of rows.slice(1).entries()) {
  const pick = (key) => (idx[key] === -1 ? "" : (row[idx[key]] ?? "").trim());

  const name = pick("name");
  if (!name) {
    console.warn(`Row ${i + 2}: blank name — skipped.`);
    continue;
  }

  let slug = pick("slug") || slugify(name);
  if (seen.has(slug)) {
    // Two guests with the same name still need distinct links.
    const n = seen.get(slug) + 1;
    seen.set(slug, n);
    slug = `${slug}-${n}`;
  } else {
    seen.set(slug, 1);
  }

  const seats = Number.parseInt(pick("seats"), 10);
  guests.push({
    slug,
    salutation: pick("salutation") || "Dear",
    name,
    seats: Number.isFinite(seats) && seats > 0 ? seats : 2,
    luckyNumber: pick("lucky") || null,
    note: pick("note") || undefined,
  });
}

const body = guests
  .map((g) => {
    const lines = [
      `    slug: ${JSON.stringify(g.slug)},`,
      `    salutation: ${JSON.stringify(g.salutation)},`,
      `    name: ${JSON.stringify(g.name)},`,
      `    seats: ${g.seats},`,
      `    luckyNumber: ${JSON.stringify(g.luckyNumber)},`,
    ];
    if (g.note) lines.push(`    note: ${JSON.stringify(g.note)},`);
    return `  {\n${lines.join("\n")}\n  },`;
  })
  .join("\n");

const out = `/**
 * GUEST REGISTRY — generated by scripts/import-guests.mjs.
 *
 * Regenerate with:  npm run guests:import -- <path-to.csv>
 * Hand edits to this file are overwritten on the next import.
 *
 * Every entry becomes a prerendered page at /<slug>, and every RSVP is filed
 * against that slug. See docs/RSVP_SETUP.md.
 */

export const guests = [
${body}
];

const bySlug = new Map(guests.map((g) => [g.slug, g]));

export function getGuest(slug) {
  return bySlug.get(slug) ?? null;
}

export function allSlugs() {
  return guests.map((g) => g.slug);
}
`;

writeFileSync("src/data/guests.js", out, "utf8");
console.log(`Wrote ${guests.length} guests to src/data/guests.js`);
console.log("Sample links:");
for (const g of guests.slice(0, 5)) console.log(`  /${g.slug}   ${g.name}`);
