#!/usr/bin/env node
/**
 * Refresh src/data/guests.js from the couple's Google Sheet.
 *
 *   npm run guests:snapshot
 *
 * The sheet is the source of truth at runtime; this only records a copy in git
 * so every invitation link still resolves if Google is unreachable when a cold
 * server instance starts. Run it before a deploy, or whenever the list has
 * changed a lot. Never edit src/data/guests.js by hand.
 *
 * Reads RSVP_WEBHOOK_URL and RSVP_SHARED_SECRET from .env.local.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { exit } from "node:process";

const env = loadEnv(".env.local");
const endpoint = process.env.RSVP_WEBHOOK_URL || env.RSVP_WEBHOOK_URL;
const secret = process.env.RSVP_SHARED_SECRET || env.RSVP_SHARED_SECRET;

if (!endpoint) {
  console.error("RSVP_WEBHOOK_URL is not set — see docs/RSVP_SETUP.md.");
  exit(1);
}

const res = await fetch(endpoint, {
  method: "POST",
  headers: { "Content-Type": "application/json" },
  body: JSON.stringify({ action: "guests", secret }),
});

const body = await res.json().catch(() => null);
if (!body?.ok) {
  console.error("Sheet read failed:", body?.error ?? `HTTP ${res.status}`);
  exit(1);
}

const guests = (body.guests ?? []).filter((g) => g.slug && g.name);
if (guests.length === 0) {
  console.error("Sheet returned no guests — refusing to write an empty snapshot.");
  exit(1);
}

const rows = guests
  .map((g) => {
    const seats = Number.parseInt(g.seats, 10);
    return [
      "  {",
      `    slug: ${JSON.stringify(g.slug)},`,
      `    name: ${JSON.stringify(g.name)},`,
      // The access code, so the gate still works during a sheet outage.
      `    code: ${JSON.stringify(String(g.code ?? "").trim())},`,
      `    seats: ${Number.isFinite(seats) && seats > 0 ? seats : 2},`,
      `    lang: ${JSON.stringify(g.lang === "vi" ? "vi" : "en")},`,
      "  },",
    ].join("\n");
  })
  .join("\n");

writeFileSync(
  "src/data/guests.js",
  `/**
 * GUEST SNAPSHOT — offline fallback, not the source of truth.
 *
 * Generated by scripts/snapshot-guests.mjs from the couple's Google Sheet.
 * The live list is read at runtime by src/lib/guest-registry.js; this copy is
 * only reached when the sheet cannot be. Hand edits are overwritten.
 *
 * Regenerate with:  npm run guests:snapshot
 */

export const snapshot = [
${rows}
];
`,
  "utf8",
);

console.log(`Wrote ${guests.length} guests to src/data/guests.js`);

/** Minimal .env reader — no dependency, and dotenv isn't installed. */
function loadEnv(file) {
  let text = "";
  try {
    text = readFileSync(file, "utf8");
  } catch {
    return {};
  }
  const out = {};
  for (const line of text.split("\n")) {
    const match = /^\s*([A-Z0-9_]+)\s*=\s*(.*)$/.exec(line);
    if (!match) continue;
    out[match[1]] = match[2].trim().replace(/^["']|["']$/g, "");
  }
  return out;
}
